language: php

php:
    - 7.3
    - 7.4
    - 8.0

# run build against nightly but allow them to fail
matrix:
    fast_finish: true
    # allow_failures:
    # only one build will send the coverage, this'll speed up other one
    # include:

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer self-update

install:
    - composer install --no-interaction --prefer-dist -o

before_script:
    - mkdir -p build/logs # Create a folder to store clover files

script:
    - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - travis_retry php vendor/bin/php-coveralls -v
